In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [2]:
df=pd.read_csv('C:\\Users\\MERINA ANGEL\\Downloads\\Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
#tenure participant yrs
#business probelm=client get churned or not

In [5]:
import os

In [6]:
x=df.iloc[:,3:-1].values
y=df['Exited'].values

In [7]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

# encoding the categorical data

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [10]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [12]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=9)

In [14]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

# building the ANN

intializing the ann using sequential

In [15]:
ann=tf.keras.models.Sequential()

adding the input layer and hidden layer 1

In [16]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#using dense we can specify how many hidden neurons are needed

adding hidden layer 2

In [17]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
#binary classification

# training the ANN

compiling the ANN

In [19]:
#training the ann
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=[{'accuracy':'accuracy'}])
#backward propagation
# we are saying to use this parameters
#hyper parameter tunning==> changing the parameters to increase accuracy

In [20]:
import os

training the ANN on training set

In [21]:
ann.fit(x_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
536/536 [==============================] - 1s 1ms/step - loss: 0.5333 - accuracy: 0.7602 - val_loss: 0.4653 - val_accuracy: 0.8008
Epoch 2/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4535 - accuracy: 0.7972 - val_loss: 0.4368 - val_accuracy: 0.8023
Epoch 3/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4299 - accuracy: 0.8024 - val_loss: 0.4198 - val_accuracy: 0.8198
Epoch 4/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4111 - accuracy: 0.8182 - val_loss: 0.4034 - val_accuracy: 0.8232
Epoch 5/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3907 - accuracy: 0.8306 - val_loss: 0.3844 - val_accuracy: 0.8357
Epoch 6/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3749 - accuracy: 0.8384 - val_loss: 0.3718 - val_accuracy: 0.8425
Epoch 7/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3652 - accuracy: 0.8410 - val_loss: 0.3647 - val_accuracy: 0.8470

In [22]:
#batch -->batching
#epoch-->iterations in which we are passsing all the batches

In [23]:
ann.predict(ss.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5
#prediction to give credit card or not to give
#o.5 is a threshold
#training data prediction is done on standardscaler

1/1 [==============================] - 0s 88ms/step


array([[False]])

# prediction on test results

In [24]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>=0.5)

63/63 [==============================] - 0s 1ms/step


In [25]:
y_pred=(y_pred>0.5)

In [26]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [28]:
confusion_matrix(y_pred,y_test)

array([[1523,  225],
       [  55,  197]], dtype=int64)

In [29]:
accuracy_score(y_pred,y_test)

0.86